image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - ms-vscode.cpptools
    - llvm-vs-code-extensions.vscode-clangd
    - ms-vscode.cmake-tools
    - editorconfig.editorconfig
    - eamodio.gitlens